### ISSUE TITLE
How to structure the cookbook?

### ISSUE THREAD

**Issue by bebraw** [christianalfoni/react-webpack-cookbook#1]
I did some initial stab at the wiki. I guess it can grow from that. Basic structure:

* General
* React.js
* <tool/environment specific>

Recipes should go beyond each. One alternative would be to think up a format that allows recipes to be tagged (can belong to multiple). Then you could implement a filtering UI based on that. But that's not needed yet and can be thought about later on.

**Comment by christianalfoni** [comment]
Hi @bebraw,

Finally, got some time with this :-)

That sounds great! I will start adding some content, and then we just keep iterating.

**Comment by bebraw** [comment]
Time to close this.
