### ISSUE TITLE
Artifacts is spelled incorrectly on the Introduction to Webpack page.

### ISSUE THREAD

**Issue by ronnross** [christianalfoni/react-webpack-cookbook#10]
Artifacts is spelled artefacts on the Introduction to Webpack page.

**Comment by bebraw** [comment]
Artefact is the British spelling. That said I don't mind doing the change. Maybe we should stick with American spelling for the whole guide?

**Comment by bebraw** [comment]
Fixed. Let's try to stick with US (bigger country!).

**Comment by ronnross** [comment]
bebraw, I'm sorry I presumed it was misspelled. I will make sure I look up the British version next time before commenting. Two countries separated by a common language, no?

**Comment by bebraw** [comment]
@ronnross It's ok. Feel free to point these things out. We can stick with US spellings for consistency. :)
