### ISSUE TITLE
How to run noParse react together with react-hot-module-replacement

### ISSUE THREAD

**Issue by abergs** [christianalfoni/react-webpack-cookbook#16]
Tried to combine these two techniques and I ended up in a fiery of flames and agony ;)

A lot of `Module not found: Error: Cannot resolve 'file' or 'dictionary C:\foo\bar\node_modules\react\dist\react.min.js/lib/ReactMount in foo.jsx`

**Comment by gaearon** [comment]
Not sure you can do both easily. What's the use case?

Normally you'd use `noParse` on some vendor files, and `react-hot-loader` should have `exclude: /node_modules/` in the configuration so it only processes files of your app.

**Comment by abergs** [comment]
Well the use case is that I want to have faster "rebuilds" on change and I want to hot-update the module. Currently a rebuild is 10s. That's slow, might be because we utilize jsx?harmony and typescript and less. Wanted to try having noPars for react lib and see if that speed thing up.

I haven't added the exclude rule to react-hot-loader, i'll try it out and get back to you.

**Comment by gaearon** [comment]
So you want to use precompiled version of React? In this case you'll need to jump through some extra hoops to get RHL working. See [usage with external React](https://github.com/gaearon/react-hot-loader/tree/master/docs#usage-with-external-react).

**Comment by abergs** [comment]
Actually tried that before, same issue. Perhaps I made some error.

**Comment by gaearon** [comment]
You need to alias `react/lib` to point to actual React NPM distribution if you're using `noParse`.
Something like `'react/lib': 'react/../lib`.

**Comment by christianalfoni** [comment]
Hi there!

@abergs Also make sure you exclude node_modules folder on loaders for typescript, babel etc. Or else all node_modules will transpiled too, takes a lot of time :-)

**Comment by abergs** [comment]
@christianalfoni Sounds like something we should definitely do, however, applying it didn't change anything.

Still around ~45s to do initial build.. We run JSX, Typescript and Less transforms. And applying exclude to all those loaders didn't change anything.

**Comment by gaearon** [comment]
@abergs How many modules do you have? ~45s warming up sounds reasonable for an app with ~1000 modules. Rebuilds should take ~1 sec then.

**Comment by christianalfoni** [comment]
@abergs Btw, A lot of Module not found: Error: Cannot resolve 'file' or 'dictionary C:\foo\bar\node_modules\react\dist\react.min.js/lib/ReactMount in foo.jsx. You have to alias 'react/lib/ReactMount' to its correct path too.

**Comment by christianalfoni** [comment]
@abergs Are you able to paste your config file and package json file with all its deps here?

**Comment by abergs** [comment]
@gaearon Ok! Well, I think WebPack reports about ~800 of them.

@christianalfoni Sure! Would be great to have someone with insight see what shenanigans I have done :) Here it is: https://gist.github.com/abergs/e186008d4aea94567432

**Comment by abergs** [comment]
Also @christianalfoni I tried adding the exclude for /node_modules/ but I didn't see any improvements at all.

**Comment by christianalfoni** [comment]
Hi @abergs ,

I know what is wrong!

devtool: 'source-map'

You have to use 'eval' when developing or things will be really slow :-)

**Comment by abergs** [comment]
Hey @christianalfoni and thanks for the tip. It does indeed speed things up quite a lot, about 9 seconds faster! However, we do not get source maps in the browser. All the requests for said source maps returns 404. (webpack:///source/application/models/immutableSomething.js.map)

**Comment by christianalfoni** [comment]
Hi again @abergs,

Yeah, there should not be any loading of sourcemaps actually. It wraps all code in eval statements and figures out the correct filename and line based on that. That is why it is very important to only do in development :-) 

Have you tried giving it an error and see what it prints out in the console? It should just work.

**Comment by abergs** [comment]
Aha, well, console.logs do work, but not when "opening" the file. We often have a workflow where we move around in our typescript files inside the browser. And for that workflow to work, we can't use eval. Good to know we cna atleast get files + linenumbers with the eval solution! :) Thanks for your insights!

**Comment by christianalfoni** [comment]
@abergs Aha! I see, yeah, that would not work then I suppose :-)

There are other sourcemap solutions too, but I have not researched any of them: http://webpack.github.io/docs/configuration.html#devtool. Let me know if you find something that fits your scenario :-)

**Comment by bebraw** [comment]
@abergs Source maps got cheap variants in a recent release. You can see up to date docs at https://github.com/webpack/docs/wiki/configuration#devtool . See esp. the table. I'm not sure how often the official site gets updated...

**Comment by ThomWright** [comment]
I found the following entry in my config worked:

```
resolve: {
  alias: {
    'react/lib': path.resolve(node_modules, 'react/lib')
  }
}
```

**Comment by christianalfoni** [comment]
Think we can close this?

**Comment by uzarubin** [comment]
@ThomWright I tried your approach, but it still wasn't working. I had aliases setup for `react` and `react-router`, with `react/lib` below them. 


Not working
```
 resolve: {
    alias: {
      'react': reactPath,
      'react-router': reactRouterPath,
      'react/lib': reactLibPath
    }
  }
```

Once I moved `react/lib` above react everything started to work

Working
```
 resolve: {
    alias: {
      'react/lib': reactLibPath
      'react': reactPath,
      'react-router': reactRouterPath,
    }
  }
```

**Comment by bebraw** [comment]
@uzarubin Yeah, that makes sense given in the first configuration it matched to `react` before getting to `react/lib`. First match wins.
