### ISSUE TITLE
Figure out what sort of recipes to gather?

### ISSUE THREAD

**Issue by bebraw** [christianalfoni/react-webpack-cookbook#2]
It might be a good idea to contact some webpack users to figure out common tasks/problems and how they solve them.

**Comment by christianalfoni** [comment]
That is a great idea! One way to do that is add some initial content and invite people in from twitter, encourage them to add issues on th wiki about missing tasks/problems, which can be discussed and then included in the cookbook.

What do you think?

**Comment by bebraw** [comment]
Sounds good. I already poked @gaearon about it and the response was positive. :)

**Comment by bebraw** [comment]
Closing. Specific ideas can be gathered into separate issues.
