### ISSUE TITLE
Introduction-to-React-JS: Invisible code examples

### ISSUE THREAD

**Issue by sibex** [christianalfoni/react-webpack-cookbook#20]
The code examples in _Basics of JSX_ are invisible. The code is not formatted or escaped.
https://christianalfoni.github.io/react-webpack-cookbook/Introduction-to-React-JS.html

**Comment by bebraw** [comment]
Thanks for the report!

Btw I have lot more React stuff at [my book (wip)](https://github.com/survivejs/webpack_react). :)

**Comment by sibex** [comment]
Stared :)
