### ISSUE TITLE
Issues Getting Started

### ISSUE THREAD

**Issue by mac10688** [christianalfoni/react-webpack-cookbook#27]
I'm running Ubuntu 14.04

Here is a screenshot

![image](https://cloud.githubusercontent.com/assets/2703261/8223598/a24e93cc-153f-11e5-8729-602128f06a44.png)

I made the file structure as the book described and copy and pasted the code. I tried many variations to try to get it to find the main.js file but it won't. I have made this work before by putting the entry file in the root folder.

**Comment by bebraw** [comment]
@mac10688 Can you push that project to GitHub? Easier to debug.

**Comment by mac10688** [comment]
I didn't fill out the package.json. I don't know how that stopped but but I guess that's the only difference. I did have to install webpack globally to get it to build with command line. I could be missing something though. I'll go ahead and close this then.

**Comment by bebraw** [comment]
Oh, okay, good to know. In practice you shouldn't have to rely on global install as that's brittle. Note that I go into more detail at survivejs.com so you might want to check that out for some further approaches.
