### ISSUE TITLE
Lazy load + multiple end points

### ISSUE THREAD

**Issue by chemoish** [christianalfoni/react-webpack-cookbook#39]
I have yet to see an example that combines...

- Multiple end points (main, Home, Admin)
- Common.js pulled out of the multiple end points (Shared)
- Lazy load the endpoints that you created (Home, Admin)

SEE: 7, 8, 9 https://github.com/petehunt/webpack-howto

Looking into some of your issues/questions/articles and they all point to the same things.

Home/Admin has duplicate code and there is only ever one entry point.

Do you know if this is possible?

Thanks!

**Comment by bebraw** [comment]
I don't see why something like this wouldn't be possible. Would it be possible for you to give it a go and link me to the repo when you get stumped with something?

**Comment by chemoish** [comment]
Hi @bebraw,

https://github.com/chemoish/react-webpack.git

Commits are segmented in the order I am following his article.

Eventually, I would like to figure out routing and isomorphic design (which i think pete-hunt just published something this weekend).

**Comment by chemoish** [comment]
![screen shot 2015-08-10 at 11 20 09 am](https://cloud.githubusercontent.com/assets/549319/9179498/d5ae15a8-3f51-11e5-83cf-f7001161a845.png)

It also looks like its being wrapped in `webpackJsonp`, which is probably the culprit.

**Comment by bebraw** [comment]
If you relax the multiple entry point requirement, you get

```diff
diff --git a/package.json b/package.json
index 1b5c7a8..a123588 100644
--- a/package.json
+++ b/package.json
@@ -4,6 +4,7 @@
   "description": "Testing out react-webpack: http://christianalfoni.github.io/javascript/2014/12/13/did-you-know-webpack-and-react-is-awesome.html",
   "main": "index.js",
   "scripts": {
+    "build": "webpack",
     "dev": "webpack-dev-server --devtool eval --progress --colors --content-base build",
     "test": "echo \"Error: no test specified\" && exit 1"
   },
diff --git a/webpack.config.js b/webpack.config.js
index 8b47910..54fd39a 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -8,8 +8,8 @@ module.exports = {
         ],
 
         app: './src/app.js',
-        pageHome: './src/components/home.js',
-        pageSetting: './src/components/setting.js'
+        //pageHome: './src/components/Home.js',
+        //pageSetting: './src/components/Setting.js'
     },
 
     output: {
```

You can try applying that with `git apply`.

There was a conflict between entry points and `CommonsChunkPlugin` so I needed to comment out the entry points.

Now the question is can we find some acceptable compromise here given that's not possible?

**Comment by chemoish** [comment]
So, do I understand correctly that you cannot achieve…

Multiple entry points (bundles), which have their common code extracted, and then the bundles themselves lazy loaded when necessary?

I have already went through consolidating it down to one entry point (which there are many examples of out there), but then you cannot extract out common code from said entry points.

`Shared.js` gets embedded per lazy loaded file.

**Comment by bebraw** [comment]
Yeah, some kind of a compromise is needed by the looks of it unless I'm understanding something wrong. One way to work around the entry restriction would be to generate separate bundles per entry. You can achieve this with some extra fiddling (run webpack through Node cli and alter entry).

**Comment by chemoish** [comment]
Darn. It was so close to being perfect.

I'll inquire how Pete hunt is achieving it in his how to examples.

Thanks.
