### ISSUE TITLE
Split app and vendors : ensure loading order

### ISSUE THREAD

**Issue by nMustaki** [christianalfoni/react-webpack-cookbook#40]
Hi,

thanks for the cookbook !
I have an issue with the receipt spliting app and vendor : my vendor.js is way larger than my app.js and so is loaded after the application code, triggering of course a "webpackJsonp is not defined" exception. Is there a Webpack way to deal with this ?

Thanks !

**Comment by bebraw** [comment]
@nMustaki Can you try https://github.com/webpack/webpack/issues/368#issuecomment-49553663 ?

**Comment by nMustaki** [comment]
Hi,

thanks for the quick answer !
Sadly this doesn't fix my issue :  my vendor.js file is downloaded by the browser after the app.js .
Any other idea ?

Thanks again,
Nathan

**Comment by bebraw** [comment]
@nMustaki Please see [code splitting](https://webpack.github.io/docs/code-splitting.html). Particularly `require.ensure`.

**Comment by nMustaki** [comment]
Ok thanks !

**Comment by af7** [comment]
@bebraw I have the same issue, I am not sure where I should be using the require.ensure, you do not seem to be using this in our Kanbap_app source code example.

**Comment by bebraw** [comment]
@af7 Yeah, Kanban doesn't need `require.ensure` as there are not dynamic dependencies in the project yet. Using it would definitely guarantee loading order.

Related issue: https://github.com/webpack/webpack/issues/368 .

**Comment by af7** [comment]
@bebraw I am using ES6 so everyhthing in my code s with the "Import" statement. I am not sure how and why I should use the "require.ensure", it is just a React application where the "vendor" code goes to "vendor.js". Thanks!

**Comment by bebraw** [comment]
@af7 See [the docs](https://webpack.github.io/docs/code-splitting.html#require-ensure). If you want to use code splitting, you'll have to mix `require.ensure` with ES6 style code. No way around that until we get Webpack 2. The use case is a little different than for vendor bundle splitting but it's good to know regardless.

**Comment by af7** [comment]
Ok, thanks, it appears that this had to do with the configuration of the webpack.config.babel.js file rather with the require.ensure.

**Comment by beeva-franciscocalle** [comment]
I had the same issue. In my case, I added `webpackJsonp` to the except section of the `UglifyJsPlugin` as opposed to what [the section in the book](http://survivejs.com/webpack/building-with-webpack/minifying-build/) suggests

```js
exports.minify = function() {
  return {
    plugins: [
      new webpack.optimize.UglifyJsPlugin({
        compress: {
          warnings: false,
          drop_console: true,
        },
        mangle: {
          props: /matching_props/,
          except: [
            'Array', 'BigInteger', 'Boolean', 'Buffer',
            'webpackJsonp', 'exports', 'require',
          ]
        }
      })
    ]
  };
}
```

**Comment by bebraw** [comment]
@beeva-franciscocalle I have fixed this for the next edition. It looks like if we add `mangle`, it will mangle Webpack runtime. The section will receive other improvements as well. Thanks for pointing this out. 👍

**Comment by maciej-gurban** [comment]
Is using `require.ensure` for dynamic module loading still the preferred way or should `import()` be used now? I tried using `module()` and either it's very buggy, or I'm doing something fundamentally wrong. I'm just trying to load two modules into one app, and it's behaving very oddly.

Here's a related [issue](https://github.com/webpack/webpack/issues/4894) and a repo showcasing the [problem](https://github.com/maciej-gurban/multi-app/tree/webpack-err)

Any chance you could give any pointers @bebraw?

**Comment by bebraw** [comment]
@maciej-gurban `import()` is the preferred way. Can you to import against library output (say use `umd` or some other variant as discussed in the [output chapter](https://survivejs.com/webpack/output/library-output/))? You probably want to use `externals` as well to manage `node_modules`. I think in your current setup webpack bootstrap might fight back and lead to the issues you are seeing.
