### ISSUE TITLE
loader for jsx

### ISSUE THREAD

**Issue by khyamay** [christianalfoni/react-webpack-cookbook#41]
Hi there I have been following this cookbook, I know babel-loader is used for parsing jsx but in section 3.1 Loading CSS, on the the webpack.config.js loader for jsx is changed to 'jsx' from 'babel', and I get error when running npm run dev. But if i put 'babel', it work fine. Do I need to install jsx-loader but I guess we dont need that as we already have bable-loader doing same thing. Am i missing something or should be it 'babel' instead of 'jsx'. Thanks.

**Comment by bebraw** [comment]
Yeah, it's better to use Babel instead. I dropped `jsx-loader` references from the book as that's obsolete.

Note that you can find more up to date approach at [my current book](http://survivejs.com/webpack_react/developing_with_webpack/).

**Comment by khyamay** [comment]
ok thanks
