### ISSUE TITLE
Using .min react alias in dev prevents warning from propTypes validation

### ISSUE THREAD

**Issue by rhysburnie** [christianalfoni/react-webpack-cookbook#44]
Hi,

If I setup the recommended alias for react in dev mode all works fine except any warning you may receive prom react propTypes do no occur.

For example I had this for an ImageItem component:

ImageItem.propTypes = {
  src: React.PropTypes.string.isRequired
};

and purposely used this: <ImageItem /> (no props)

With the alias in place it all works fine but you get no warnings.

When I remove the alias I get the expected warning:
Warning: Failed propType: Required prop `src` was not specified in `ImageItem`. Check the render method of `Root`.

I thought I'd just mention this because if using the minified version suppresses warnings it kinda defeats the purpose since you want to see these things in dev mode.

Cheers

**Comment by bebraw** [comment]
The problem is that `react.min.js` is a production build (type checks disabled).

I'm not sure if there's an easy way around this. I suppose you could generate a minified version of `dist/react.js` while env is not set to production. There probably would have to be a separate task for that. You could then point to this version instead.

**Comment by rhysburnie** [comment]
Yep thanks I knew what the problem is, I guess my point was if the warnings are suppressed perhaps the recommendation to use the .min version in development should be removed and use something else for an alias example. 
With the way it is now its possible that people following the example setup dev that way and assume their components are fine due to errors being suppressed.  It's just a little counter productive developing with the react core in production mode.
Since it suppresses the warning designed to help develop I think it would be better if the book didn't recommend using the .min version.

**Comment by bebraw** [comment]
Yeah, that's a very valid point. I'll add a warning about this as it's easy to miss the behavior.
