### ISSUE TITLE
Add React Hot Loader instructions

### ISSUE THREAD

**Issue by gaearon** [christianalfoni/react-webpack-cookbook#5]
It would be nice to add this guide: http://gaearon.github.io/react-hot-loader/getstarted/

**Comment by bebraw** [comment]
I linked to it at https://github.com/christianalfoni/react-webpack-cookbook/wiki/Optimizing-development . There's not other content there but I think @christianalfoni will expand the section at some point.

Of course if you want to throw in some pointers, go ahead.

**Comment by gaearon** [comment]
OK, thanks! BTW index page for that section doesn't work: https://github.com/christianalfoni/react-webpack-cookbook/wiki/Advanced

**Comment by christianalfoni** [comment]
Hi there,

Yeah, I have big plans for that section :-) Using it on a project now and its freakin awesome.
