### ISSUE TITLE
Set up a webhook to update gh-pages on wiki update

### ISSUE THREAD

**Issue by bebraw** [christianalfoni/react-webpack-cookbook#7]
I just got a tip it should be possible to set up gh-pages to update by subscribing to `gollum` [webhook](https://developer.github.com/webhooks/).

In our case it would have to trigger `npm run gitbook && npm run deploy`.

@christianalfoni Do you have experience with webhooks?

**Comment by christianalfoni** [comment]
Hm, no sorry, no experience in that area :-/

**Comment by bebraw** [comment]
Ok, no probs!

**Comment by bebraw** [comment]
Closing given there's a cronjob to deal with this now.
